version: '3'

services:
    nodejs:
        build: .
        restart: unless-stopped
        ports:
        - "5000:3000"
    db:
        image: mongo:4.1.8-xenial
        restart: unless-stopped
        volumes:  
          - ./dbdata:/data/db   
        container_name: db